package com.xtopdf.xtopdf.contract;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;

/**
 * Provider verification test for the XToPDF API.
 *
 * <p>Verifies that the running application fulfills the contracts defined by consumers.
 * This test starts the full Spring Boot application and verifies the Pact contracts
 * stored in the build/pacts directory (generated by PactConsumerTest).
 *
 * <p>To run this test:
 * 1. First run PactConsumerTest to generate pact files
 * 2. Then run this test to verify the provider meets the contract
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Provider("xtopdf-provider")
@PactFolder("build/pacts")
class PactProviderTest {

  @LocalServerPort private int port;

  @BeforeEach
  void setUp(PactVerificationContext context) {
    if (context != null) {
      context.setTarget(new HttpTestTarget("localhost", port));
    }
  }

  @TestTemplate
  @ExtendWith(PactVerificationInvocationContextProvider.class)
  void verifyPact(PactVerificationContext context) {
    if (context != null) {
      context.verifyInteraction();
    }
  }

  @State("the conversion service is available")
  void conversionServiceAvailable() {
    // No setup needed — the Spring Boot app starts with all converters registered
  }
}
