package com.xtopdf.xtopdf.enums;

public enum PageNumberStyle {
    ARABIC,           // 1, 2, 3, ...
    ROMAN_UPPER,      // I, II, III, ...
    ROMAN_LOWER,      // i, ii, iii, ...
    ALPHABETIC_UPPER, // A, B, C, ...
    ALPHABETIC_LOWER  // a, b, c, ...
}
